### ISSUE TITLE
T-spin problems

### ISSUE THREAD

**Issue by bmjeon5957** [Porowl/JS-PPT#1]
1. T-spin Double and T-spin Triple both does only 1 and 2 damage respectively

2. T-spins do not receive Back to Back damage

Easy to replicate, no furthur explaination needed

**Comment by bmjeon5957** [comment]
클론 후 직접 열어서 테스트해본 결과로는 정상적으로 적용되네요. 혹시 jsppt.ga의 코드와 리포에 올라와 있는 코드가 다를까요?

**Comment by Porowl** [comment]
jsppt.ga 코드 최신버전으로 업데이트 했습니다.
