### ISSUE TITLE
Bubbling -> Tetrocks attack garbage delays for too long

### ISSUE THREAD

**Issue by bmjeon5957** [Porowl/JS-PPT#10]
버블링이 터트록스를 큰 콤보로 공격했을 때, 한번에 8줄씩만 올라오는 건 맞는데, 테트록스가 블럭을 수 회 놓을떄까지 다음 쓰레기줄이 올라오지 않습니다. 보통은 블럭 한번 놓을떄마다 쓰레기줄 한번씩 올라와야 합니다. (콤보 수에 비례하는 느낌이 드는데 관련이 있을 것 같아요)

**Comment by Porowl** [comment]
버블링이 체인을 끝날 때 까지 공격이 안 들어가도록 만들어 놨는데
이 떄문에 버블링이 다음 공격할 때 까지 제대로 판정이 안 들어가서 생긴 버그입니다. 
이미 쓰레기가 쌓여있는 상태에서 버블링이 공격 시 판정이 어떻게 되는지를 제대로 알아보고 고치겠습니다.

**Comment by Porowl** [comment]
Changes in commit 0d61a13 should have fixed this issue.
