### ISSUE TITLE
Opponent disconnecting stalls the game permanantly / long enough

### ISSUE THREAD

**Issue by bmjeon5957** [Porowl/JS-PPT#3]
How to replicate

1. Get matched with yourself using 2 browsers
2. Exit on other browser
3. Game permanantly stalled (or at least for 3 minutes)

**Comment by Porowl** [comment]
The app doesn't have a function to react to the disconnection of the users at the moment, and the players would have to manually refresh the page to select the game board they want to play and enter the queue. It'll be added soon.
