### ISSUE TITLE
Cannot counter incoming garbage / garbage in queue

### ISSUE THREAD

**Issue by bmjeon5957** [Porowl/JS-PPT#6]
Easy to replicate

1. Player 1 perform Tspin double -> 4 Attack to Player 2

2. Player 2 perform Tspin double -> Instead of cancelling garbage out, it instead throws 4 attacks to player 2 and receives 4 blocks in his field

I haven't tried to counter when the garbage is technically "flying" to the other player (realistically impossible to test alone), but at least after it's arrived it cannot be countered

상쇄가 안됩니다. 날아오는 도중에까진 혼자라서 못해봤는데, 일단 쓰레기줄이 도착하고 나서는 확실히 안되는것으로 보입니다.

**Comment by Porowl** [comment]
버그 수정 완료
