### ISSUE TITLE
Animation glitch if you gain garbage line while clearing a line

### ISSUE THREAD

**Issue by bmjeon5957** [Porowl/JS-PPT#7]
1. Player 1 performs T-spin double -> 4 attacks to Player 2

2. Player 2 performs a line clear

3. Line clear animation (some flashing for the piece that made line clear happen) appears 4 blocks higher than where it should

공격받고 나서 쓰레기줄이 올라오기 전에 줄을 지우면, 라인클리어시 발생하는 반짝이는 그림자 (예 : I미노로 지웠으면 I미노 모양, T미노로 지웠으면 T미노 모양으로 빛나는 거) 가 쓰레기줄이 올라온 후의 위치에 생깁니다.

**Comment by bmjeon5957** [comment]
![image](https://user-images.githubusercontent.com/29906997/113138145-5d042300-9260-11eb-9cbb-79991789e895.png)

**Comment by Porowl** [comment]
애니메이션 부분은 전체적으로 다시 코드를 짜야 해서 내버려두고 있습니다.
