### ISSUE TITLE
Bubbing preview randomizes once again before the game starts

### ISSUE THREAD

**Issue by bmjeon5957** [Porowl/JS-PPT#9]
1. Start a game as bubbling
2. Preview bubbling changes after the countdown, causing confusion

Solution

1. Block preview before the countdown (just like tetrocks)
OR
2. Let tetrocks also see preview, and don't randomize bubbling after the countdown

카운트다운 전에 버블링 프리뷰가 보이는데 이게 카운트다운 끝나면 갑자기 셔플돼서 혼동이 옵니다. 테트록스처럼 프리뷰를 가리거나, 아니면 아예 테트록스도 프리뷰를 열어주고 카운트다운 후에 셔플이 안 되게 하거나. 

실제 뿌테의 경우 ready, go 전부터 프리뷰가 보이기 시작합니다. 저는 2)를 추천합니다.

**Comment by Porowl** [comment]
Chose Solution 2 and fixed.
